version: "3.7"
services:
  frontend:
    build:
      context: ./WeBuy_Frontend/
      dockerfile: Dockerfile
    ports:
      - "80:80"
  backend:
    build:
      context: ./WeBuy_Backend/
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/WeBuy
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: WeBuy
    ports:
      - "5432:5432"
